steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/leystar-api:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/leystar-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'leystar-api'
      - '--image=gcr.io/$PROJECT_ID/leystar-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/leystar-api:$COMMIT_SHA'

substitutions:
  _GCS_BUCKET_NAME: ley-star  # Default value, can be overridden

options:
  logging: CLOUD_LOGGING_ONLY