# .github/workflows/deploy.yml
name: Deploy Leystar

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend-update]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone minimal frontend repo
        run: |
          git clone https://github.com/oliverwstein/minimal-sveltekit-test.git frontend/src  # Correct URL

      - name: List Files (Debugging)
        run: |
          echo "Files in /workspace:"
          ls -l /workspace
          echo "Files in /workspace/frontend:"
          ls -l /workspace/frontend
          echo "Files in /workspace/frontend/src:"
          ls -l /workspace/frontend/src

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run (Submit Only)
        run: |
          gcloud builds submit frontend --config=frontend/cloudbuild.yaml --async
          BUILD_ID=$(gcloud builds list --limit=1 --format='value(id)')
          echo "Build ID: $BUILD_ID"