# .github/workflows/deploy.yml
name: Deploy Leystar

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend-update]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone frontend repo
        run: |
          git clone --branch gcloud https://github.com/oliverwstein/ley-star.frontend frontend/src

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
    #   - name: Deploy to Cloud Run
    #     run: |
    #         gcloud builds submit frontend --config=frontend/cloudbuild_debug.yaml --async
      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit frontend --config=frontend/cloudbuild.yaml --async
          BUILD_ID=$(gcloud builds list --limit=1 --format='value(id)')
          while true; do
            sleep 30
            BUILD_STATUS=$(gcloud builds describe "$BUILD_ID" --format='value(status)')
            echo "Build Status: $BUILD_STATUS"
            case "$BUILD_STATUS" in
              SUCCESS)
                echo "Build succeeded!"
                exit 0
                ;;
              FAILURE|INTERNAL_ERROR|TIMEOUT|CANCELLED)
                echo "Build failed with status: $BUILD_STATUS"
                gcloud builds log "$BUILD_ID"  # Show the build logs
                exit 1
                ;;
            esac
          done