# .github/workflows/deploy.yml
name: Deploy Leystar

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend-update]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone frontend repo
        run: |
          git clone https://github.com/oliverwstein/ley-star frontend/src
      
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit frontend --config=frontend/cloudbuild.yaml