# .github/workflows/deploy.yml
name: Deploy Leystar

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend-update]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create frontend directory structure
        run: |
          mkdir -p frontend/src
          
      - name: Clone frontend repo
        run: |
          git clone https://github.com/oliverwstein/ley-star.frontend frontend/src
      
      - name: Copy deployment files
        run: |
          cp frontend/src/Dockerfile frontend/
          cp frontend/src/cloudbuild.yaml frontend/

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit frontend --config=frontend/cloudbuild.yaml || true
          # Wait a bit for the build to progress
          sleep 30
          # Check the last build status
          BUILD_STATUS=$(gcloud builds list --limit=1 --format='get(status)')
          if [[ "$BUILD_STATUS" == "FAILURE" ]]; then
            exit 1
          fi