# .github/workflows/deploy.yml
name: Deploy Leystar

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [frontend-update]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Clone frontend repo
        run: |
          git clone https://github.com/oliverwstein/ley-star frontend/src
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1  # Updated to v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit frontend --config=frontend/cloudbuild.yaml